/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistrictsRouteImport } from './routes/districts'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ListingRouteImport } from './routes/listing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PostAdRouteImport } from './routes/post-ad'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UniversityHubsRouteImport } from './routes/university-hubs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsRoute = DistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingRoute = ListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAdRoute = PostAdRouteImport.update({
  id: '/post-ad',
  path: '/post-ad',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityHubsRoute = UniversityHubsRouteImport.update({
  id: '/university-hubs',
  path: '/university-hubs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRoute
  '/guides': typeof GuidesRoute
  '/listing': typeof ListingRoute
  '/login': typeof LoginRoute
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/university-hubs': typeof UniversityHubsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRoute
  '/guides': typeof GuidesRoute
  '/listing': typeof ListingRoute
  '/login': typeof LoginRoute
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/university-hubs': typeof UniversityHubsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/districts': typeof DistrictsRoute
  '/guides': typeof GuidesRoute
  '/listing': typeof ListingRoute
  '/login': typeof LoginRoute
  '/post-ad': typeof PostAdRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/university-hubs': typeof UniversityHubsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/districts'
    | '/guides'
    | '/listing'
    | '/login'
    | '/post-ad'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/saved'
    | '/search'
    | '/support'
    | '/terms'
    | '/university-hubs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/districts'
    | '/guides'
    | '/listing'
    | '/login'
    | '/post-ad'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/saved'
    | '/search'
    | '/support'
    | '/terms'
    | '/university-hubs'
  id:
    | '__root__'
    | '/'
    | '/districts'
    | '/guides'
    | '/listing'
    | '/login'
    | '/post-ad'
    | '/privacy'
    | '/refund-policy'
    | '/register'
    | '/saved'
    | '/search'
    | '/support'
    | '/terms'
    | '/university-hubs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistrictsRoute: typeof DistrictsRoute
  GuidesRoute: typeof GuidesRoute
  ListingRoute: typeof ListingRoute
  LoginRoute: typeof LoginRoute
  PostAdRoute: typeof PostAdRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  UniversityHubsRoute: typeof UniversityHubsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts': {
      id: '/districts'
      path: '/districts'
      fullPath: '/districts'
      preLoaderRoute: typeof DistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing': {
      id: '/listing'
      path: '/listing'
      fullPath: '/listing'
      preLoaderRoute: typeof ListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ad': {
      id: '/post-ad'
      path: '/post-ad'
      fullPath: '/post-ad'
      preLoaderRoute: typeof PostAdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university-hubs': {
      id: '/university-hubs'
      path: '/university-hubs'
      fullPath: '/university-hubs'
      preLoaderRoute: typeof UniversityHubsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistrictsRoute: DistrictsRoute,
  GuidesRoute: GuidesRoute,
  ListingRoute: ListingRoute,
  LoginRoute: LoginRoute,
  PostAdRoute: PostAdRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  UniversityHubsRoute: UniversityHubsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
